name: Test with Selenium and LightBDD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Install dependencies for Selenium and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip \
            libnss3 \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libnspr4 \
            libx11-xcb1
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests and generate TRX report
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx"

      - name: Install ReportGenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add tool path to environment
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate HTML report
        run: |
          reportgenerator \
            -reports:TestResults/results.trx \
            -targetdir:TestResults/Report \
            -reporttypes:HtmlInline_AzurePipelines \
            -assemblyfilters:+SeleniumTests \
            -filefilters:-*Program.cs

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: TestResults/Report/index.html