name: Test with Selenium and LightBDD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Install dependencies for Selenium and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip \
            libnss3 \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libnspr4 \
            libx11-xcb1
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests with NUnit and generate report
        run: dotnet test --configuration Release --no-build --logger "nunit;LogFilePath=./TestResults/results.xml" --verbosity normal

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/results.xml

      - name: Fallback - Print results on failure
        if: ${{ failure() }}
        run: cat ./TestResults/results.xml || echo "Test results not found."