name: Run Selenium Tests with SpecFlow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run tests and generate .trx and TestExecution.json
        run: |
          dotnet test --no-build --logger "trx;LogFileName=TestResults.trx" --logger "specflowjson;LogFileName=TestExecution.json"

      - name: Install SpecFlow+ LivingDoc CLI globally
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Add .NET tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Generate LivingDoc HTML report with test execution data
        shell: pwsh
        run: |
          $livingdocPath = "$env:USERPROFILE\.dotnet\tools\livingdoc.exe"
          if (!(Test-Path $livingdocPath)) {
            throw "LivingDoc executable not found at $livingdocPath"
          }
          & $livingdocPath test-assembly ".\bin\Debug\net8.0\SeleniumTests.dll" `
            --test-execution-json "TestExecution.json" `
            --output "LivingDoc.html"

      - name: Upload LivingDoc report
        uses: actions/upload-artifact@v4
        with:
          name: livingdoc-report
          path: LivingDoc.html

      - name: Upload test results (trx)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults.trx