name: Run Selenium Tests with SpecFlow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run tests and generate .trx report
        run: dotnet test --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Install SpecFlow+ LivingDoc CLI
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Add dotnet tools to PATH (Windows)
        shell: pwsh
        run: |
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Refresh shell to use dotnet tools
        shell: pwsh
        run: |
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
          Get-Command livingdoc

      - name: Generate LivingDoc HTML report
        shell: pwsh
        run: |
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
          dotnet livingdoc export --test-results TestResults.trx --output LivingDoc.html

      - name: Upload LivingDoc report
        uses: actions/upload-artifact@v4
        with:
          name: livingdoc-report
          path: LivingDoc.html