name: Run SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SpecFlow+ LivingDoc CLI
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Debug

      - name: Run tests and generate execution JSON
        run: dotnet test --no-build --logger "json;LogFileName=TestExecution.json"

      - name: Generate LivingDoc HTML report
        run: livingdoc test-assembly .\bin\Debug\net8.0\SeleniumTests.dll -t TestExecution.json

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: livingdoc-report
          path: LivingDoc.html
