name: Test with Selenium and LightBDD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # Certifique-se de que a versão do .NET está correta

      - name: Restore dependencies
        run: dotnet restore

      - name: Install dependencies for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests with NUnit
        run: dotnet test --configuration Release --no-build --verbosity normal